### ISSUE TITLE
Instance Missing

### ISSUE THREAD

**Issue by ytprivatecom** [iv-org/invidious-redirect#12]
Is there a reason our instance is missing from the Invidious site?

**Comment by syeopite** [comment]
Yep, we removed your instance due to it being outdated and the lack of a "changes" list. See https://github.com/iv-org/documentation/issues/131

**Comment by ytprivatecom** [comment]
What is the timeframe to be considered outdated? Apologies for not seeing the other issue, our mailbox has been getting spammed so I must have missed the notification. We're updating now and our changes are back on the README. @syeopite

**Comment by syeopite** [comment]
A month or  ~ 30 days. The rules have yet to be completely formalized but you can find a rough *draft* of them here: https://github.com/syeopite/documentation/blob/alt-instance-list/Invidious-Instances.md#prerequisites.

**Comment by ytprivatecom** [comment]
Good to know, thank you, we also no longer use any DDoS mitigation provider @syeopite
