### ISSUE TITLE
[Bug] "health" remains "unknown" for all instances

### ISSUE THREAD

**Issue by KaKi87** [iv-org/invidious-redirect#23]
And mobile UI doesn't let us see the entire URLs.

![](https://i.goopics.net/hu3fky.png)

Thanks

**Comment by unixfox** [comment]
Can't reproduce, something is wrong on your side.

![image](https://user-images.githubusercontent.com/4016501/188280824-b46699cf-43eb-4c83-838e-61763621e64f.png)

**Comment by KaKi87** [comment]
Well, I actually don't reproduce the primary bug either anymore.

However, I still reproduce the secondary bug.

Thanks

**Comment by unixfox** [comment]
> Well, I actually don't reproduce the primary bug either anymore.
> 
> However, I still reproduce the secondary bug.
> 
> Thanks

Please create another issue for that.
