### ISSUE TITLE
Definition of "healthy"

### ISSUE THREAD

**Issue by shaedrich** [iv-org/invidious-redirect#38]
**How is the health percentage calculated?**\
A server itself can _respond_ every time just fine and quite _on time_, but the instance can respond with errors caused by Google regularly.

When redirected to these instances, this can be pretty annoying. It would be nice if that would be taken into account when redirecting.

Would there be a need for URL parameters (geolocation/region, software version preference and such)?

**Comment by unixfox** [comment]
https://github.com/iv-org/instances-api/pull/44
https://github.com/iv-org/instances-api/issues/53

**Comment by shaedrich** [comment]
@unixfox Thank you for the links. However, these solutions are information-only, meaning it's _nice to have_ them in the table, but they are not changing the redirection logic if I understand that correctly. So, this isn't solving the core problem which led me to open this very issue.

**Comment by unixfox** [comment]
we can't implement the frontend feature if the backend feature doesn't exist.

**Comment by shaedrich** [comment]
Sure, but why closing this issue instead of letting it open, waiting for the linked PR to be merged and then take the information from the instance API?

**Comment by unixfox** [comment]
we will create a separate issue when the backend will be done. for the moment there are more urgent issues to solve.

**Comment by shaedrich** [comment]
Hope, I'll notice when the time comes …
